### ISSUE TITLE
Jogging forward after stopping playback seeks to wrong frame

### ISSUE THREAD

**Issue by sh0sh1n** [databrary/datavyu#246] opened 2019-06-20 22:59 UTC
**Describe the bug**
After normal playback, if the timestamp in the Controller is near a frame boundary, jogging forward actually moves back one frame.

**To Reproduce**
1. Play
2. Stop
3. Jog forward
4. Repeat 1-3 until symptom happens.

**Expected behavior**
Next frame after currently displayed frame should be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Datavyu version 1.5.0rc4

**Comment by Xubes** [comment] 2019-06-20 23:18
Also, sometimes the jog will not advance the frame. The Controller time will move forward but the displayed frame will not change. Even stranger, jogging back after this will move to the previous frame EVEN if the timestamp is the SAME as before (e.g., time a : frame 1; time a+z : frame 1, time a+z-z : frame 0).

**Comment by TheoWolf** [comment] 2019-10-23 00:17
Test if the problem is still in ffmpeg-plugin 0.22

**Comment by TheoWolf** [comment] 2019-10-24 20:39
Fixed in Datavyu 1.5.1 - ffmpeg-plugin 0.22

**Closed by TheoWolf** 2019-10-24 20:39 UTC
Labels: Platform : Win, Player : ffmpeg, Type : bug
