### ISSUE TITLE
Stuttering playback after first adding video.

### ISSUE THREAD

**Issue by Xubes** [databrary/datavyu#181] opened 2019-02-22 17:34 UTC
**Describe the bug**
Pressing play after adding a video causes playback to stutter (audio and video). Waiting several seconds before pressing play does not alleviate the issue. Tried both network media as well as local files. Problem disappears if you press stop and then press play again.

**To Reproduce**
1. Add video file (tested with both .mp4 and .mov).
2. Press play.

**Expected behavior**
Playback should proceed smoothly.

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
- Plugin: FFMPEG

**Comment by TheoWolf** [comment] 2019-02-25 16:49
This might be caused by an unresponsive video controller, the initial play signal might not get to the ffmpeg player and causes Datavyu to force a synchronization (fake playback at 1x) between the controller clock and the ffmpeg player. 
Note : A stop and play fixe the initial stuttering

**Comment by TheoWolf** [comment] 2019-03-01 22:43
The problem is located in the Datavyu player repo; the ffmpeg player changes its state from Ready to PLAYING when the a seek is performed which is causing Datavyu to ignore the first play (Note that Datavyu seek to 0.0 ss when a video is loaded which change the player state from Ready to Playing).

**Comment by TheoWolf** [comment] 2019-03-05 16:05
Fixed in https://github.com/databrary/datavyu-ffmpegplugin/pull/148/commits/9f86f37378a7681a1f9777671d5a96b9ae7ad14b

**Closed by TheoWolf** 2019-03-05 16:06 UTC
Labels: Mac, bug, ffmpeg
